version: '3.7'

services:
  mongodb:
    image: mongo:6.0
    container_name: easygen-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: easygen-mongodb